# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_int <- function(n, size, replace = FALSE) {
    .Call(`_dqsample_sample_int`, n, size, replace)
}

